"""Every project extension the suite loads must survive a fresh clone.

`.tau/` is gitignored in its entirety, so a project extension's source is not
in the repository. `tests/ext_loader.py` used to load only from there, which
made any test importing one fail on a clean checkout — and the failure looked
like a broken extension rather than an absent one.

`examples/extensions/<name>` is the tracked mirror. These tests pin the two
properties that make relying on it safe: the mirror exists for everything the
suite loads, and where both copies are present their source agrees, so the
tracked copy is not quietly a different program from the one being tested.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from tests.ext_loader import extension_dir

_ROOT = Path(__file__).parent.parent
_LOCAL = _ROOT / ".tau" / "extensions"
_MIRROR = _ROOT / "examples" / "extensions"

#: Source that must agree between the two copies. README.md is deliberately
#: excluded — `examples/` carries docs that the working copy has no need for.
_SOURCE_SUFFIXES = {".py", ".json", ".yaml", ".yml", ".md"}
_IGNORED_NAMES = {"README.md"}


def _loaded_extension_names() -> set[str]:
    """Names the suite passes to load_extension() without builtin=True."""
    names: set[str] = set()
    for path in _ROOT.glob("tests/*.py"):
        for match in re.finditer(r"load_extension\(\s*[\"'](\w+)[\"']([^)]*)\)", path.read_text()):
            if "builtin=True" not in match.group(2):
                names.add(match.group(1))
    return names


def _source_files(directory: Path) -> dict[str, bytes]:
    out: dict[str, bytes] = {}
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        if path.suffix not in _SOURCE_SUFFIXES or path.name in _IGNORED_NAMES:
            continue
        out[str(path.relative_to(directory))] = path.read_bytes()
    return out


def test_the_suite_loads_at_least_one_project_extension() -> None:
    """Guards the guard: a broken scrape would make everything below vacuous."""
    assert _loaded_extension_names()


@pytest.mark.parametrize("name", sorted(_loaded_extension_names()))
def test_a_loaded_extension_has_a_tracked_mirror(name: str) -> None:
    mirror = _MIRROR / name / "__init__.py"

    assert mirror.exists(), (
        f"tests load '{name}' from .tau/extensions, which is gitignored, and"
        f" examples/extensions/{name} does not exist — a fresh clone cannot run them"
    )


@pytest.mark.parametrize("name", sorted(_loaded_extension_names()))
def test_the_mirror_resolves_when_the_working_copy_is_absent(name: str) -> None:
    """What actually happens on a clean checkout."""
    resolved = extension_dir(name)

    assert (resolved / "__init__.py").exists()


@pytest.mark.parametrize("name", sorted(_loaded_extension_names()))
def test_the_two_copies_agree(name: str) -> None:
    """A mirror that has drifted is worse than none: it passes CI and ships stale."""
    local, mirror = _LOCAL / name, _MIRROR / name
    if not (local / "__init__.py").exists():
        pytest.skip(f"{name} has no working copy here")

    local_files, mirror_files = _source_files(local), _source_files(mirror)

    assert set(local_files) == set(mirror_files), (
        f"{name}: file sets differ — "
        f"only local: {sorted(set(local_files) - set(mirror_files))}, "
        f"only mirror: {sorted(set(mirror_files) - set(local_files))}"
    )
    differing = [k for k in local_files if local_files[k] != mirror_files[k]]
    assert not differing, f"{name}: content differs in {differing}"


def test_the_working_copy_wins_when_present() -> None:
    """Local edits are what a developer is testing; the mirror is the fallback."""
    name = "permissions"
    if not (_LOCAL / name / "__init__.py").exists():
        pytest.skip("no working copy here")

    assert extension_dir(name) == _LOCAL / name


def test_runtime_artefacts_are_not_mirrored() -> None:
    """decisions.log is a session's own history, not source.

    Only artefacts git would actually pick up are worth asserting on.
    ``__pycache__`` is matched by .gitignore and is generated by merely
    importing the mirror — including by the tests above — so its presence on
    disk says nothing. ``decisions.log`` is only ignored under ``.tau/``, so a
    copied one *would* be committed.
    """
    mirrored = _MIRROR / "permissions"
    if not mirrored.exists():
        pytest.skip("permissions is not mirrored here")

    assert not (mirrored / "decisions.log").exists()
