"""Type stubs for the `grapheme` package, which ships no py.typed.

Without these, pyright infers `graphemes()` as yielding `str | None`: the
iterator's buffer starts as `None` for an empty string (grapheme/finder.py,
`GraphemeIterator.__init__`) and `_break` hands that buffer back. In practice
`__next__` raises StopIteration while the buffer is falsy, so `None` never
escapes — but the inference cost nine `reportArgumentType` errors across
tau/tui, at every call site rather than at the boundary.

mypy already skips this package (`[mypy-grapheme]` in mypy.ini). These stubs
state the same contract for pyright, which reads the untyped source instead.
"""

from collections.abc import Iterator

UNICODE_VERSION: str

def graphemes(string: str) -> Iterator[str]: ...
def length(string: str, until: int | None = None) -> int: ...
def grapheme_lengths(string: str) -> Iterator[int]: ...
def slice(string: str, start: int | None = None, end: int | None = None) -> str: ...
def contains(string: str, substring: str) -> bool: ...
def startswith(string: str, prefix: str) -> bool: ...
def endswith(string: str, suffix: str) -> bool: ...
def safe_split_index(string: str, max_len: int) -> int: ...
